SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(BS.SALES * B.PRICE) AS TOTAL_SALES FROM BOOK B
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID
WHERE BS.SALES_DATE LIKE "2022-01%"
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY B.AUTHOR_ID asc, B.CATEGORY desc;




-- 2022년 1월의 도서 저자 별, 카테고리 별 매출액(TOTAL_SALES = 판매량 * 판매가) 구하기
-- 2022년 1월 필터, GROUP BY 저자, 카테고리