select ITEM_INFO.ITEM_ID, ITEM_INFO.ITEM_NAME from ITEM_INFO
join ITEM_TREE
on ITEM_INFO.ITEM_ID = ITEM_TREE.ITEM_ID
where ITEM_TREE.PARENT_ITEM_ID is null
order by ITEM_INFO.ITEM_ID asc



-- ROOT 아이템 구하기 PARENT_ITEM_ID가 null인 것.
-- ITEM_ID기준 오름차순 정렬