SELECT CCC.CAR_ID,
		CCC.CAR_TYPE, 
        ROUND(CCC.DAILY_FEE * 30 * (100-CRCD.DISCOUNT_RATE)/100) AS FEE 
FROM CAR_RENTAL_COMPANY_CAR as CCC 
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY as CRCRH ON CCC.CAR_ID = CRCRH.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN as CRCD ON  CCC.CAR_TYPE = CRCD.CAR_TYPE
WHERE CCC.CAR_ID NOT IN (
	SELECT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE >= '2022-11-01' and START_DATE <= '2022-12-01'
	)
	AND CRCD.DURATION_TYPE = '30일 이상'
GROUP BY CCC.CAR_ID
HAVING CCC.CAR_TYPE IN ('세단', 'SUV') AND (FEE BETWEEN 500000 and 2000000)
ORDER BY FEE desc, CCC.CAR_TYPE asc, CCC.CAR_ID desc

/*
1. CAR_TYPE은 세단, SUV인자동차
2. 2022년 11월 1일 부터 2022년 11월 30일까지 대여가능하고, 30일간 대여 금액이 50만원이상 200만원 미만인 자동차
3. 결과는 대여 금액을 기준으로 내림차순, 자동차 ㅈ종류 기준으로 오름차순, 자동차 ID로  내림차순
*/