select FOOD_TYPE, REST_ID, REST_NAME, FAVORITES from 
(SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES, RANK() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) as RANKING
    from REST_INFO
) R
WHERE R.RANKING = 1
order by FOOD_TYPE desc


-- (음식 종류 별로) 즐겨찾기수가 가장 많은 식당
-- 음식 종류 기준 내림차순