SELECT AI.ANIMAL_ID, AI.ANIMAL_TYPE, AI.NAME FROM ANIMAL_INS AI JOIN ANIMAL_OUTS AO
ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AI.SEX_UPON_INTAKE LIKE 'Intact%' and (AO.SEX_UPON_OUTCOME LIKE ('Spayed%') or AO.SEX_UPON_OUTCOME LIKE ('Neutered%'))
order by AI.ANIMAL_ID

-- 들어올때는 중성화 X, 나갈때 중성화 된 동물
-- ANIMAL_ID, ANIMAL_TYPE, NAME
-- ANIMAL_ID 기준 오름차순 정렬