-- 전체 - NULL값 미포함
SELECT COUNT(*)-COUNT(AGE) AS USERS FROM USER_INFO;

-- SUM 사용
-- SELECT SUM(AGE IS NULL) AS USERS FROM USER_INFO;

-- SELECT COUNT(CASE WHEN AGE IS NULL THEN 1 END) AS USERS FROM USER_INFO;

-- WHERE 사용
-- SELECT COUNT(*) AS USERS FROM USER_INFO
-- WHERE AGE IS NULL;