SELECT CAR_ID, round(AVG(DATEDIFF(END_DATE, START_DATE)+1), 1) as AVERAGE_DURATION FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVG(DATEDIFF(END_DATE, START_DATE)+1) >= 7
order by AVERAGE_DURATION desc, car_id desc;


-- 평균 대여 기간 7일이상 자동차들의 자동차 ID, 평균 대여 기간 출력하기(GROUP BY ID)
-- 평균대여기간은 소수점 2번째 자리에서 반올림
-- 평균대여기간 기준 내림차순, 자동차 ID 기준 내림차순


SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE)+1), 1) AS AVERAGE_DURATION FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID HAVING AVG(DATEDIFF(END_DATE, START_DATE)+1) >= 7
ORDER BY AVERAGE_DURATION desc, CAR_ID desc;