SELECT AO.ANIMAL_ID, AO.NAME FROM ANIMAL_OUTS AO LEFT JOIN ANIMAL_INS AI
ON AO.ANIMAL_ID = AI.ANIMAL_ID
WHERE AI.DATETIME is null





-- 입양을 간(ANIMAL_OUTS)기록은 있는데, 보호소에 돌어온(ANIMAL_INS)기록은 없는 동물
-- ANIMAL_ID, NAME