-- 코드를 입력하세요
-- SELECT DATETIME FROM ANIMAL_INS
-- WHERE DATETIME = (SELECT MAX(DATETIME) FROM ANIMAL_INS);




select DATETIME from ANIMAL_INS
where DATETIME = (select MAX(DATETIME) from ANIMAL_INS);