SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, "%Y-%m-%d") AS DATE_OF_BIRTH FROM MEMBER_PROFILE
WHERE TLNO is not null and GENDER = "W" and DATE_OF_BIRTH LIKE "%-03-%"
ORDER BY MEMBER_ID asc