SELECT MONTH(START_DATE) as MONTH, CAR_ID, count(*) as RECORDS FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY as CR
WHERE CAR_ID IN 
(
	SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
	WHERE MONTH(START_DATE) BETWEEN 8 AND 10
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
) 
AND MONTH(START_DATE) BETWEEN 8 AND 10
GROUP BY MONTH, CAR_ID
HAVING RECORDS != 0
ORDER BY MONTH, CAR_ID desc;


-- 대여 시작일 2022년 8월 부터 2022년 10월까지 총 대여 횟수 5회 이상인 자동차
-- 월별,자동차 ID별 총 대여횟수(컬럼 RECORDS) (대여 횟수가 0인것 은 제외)
-- 월 기준 오름차순, 아이디 기준 내림차순