select FI.ID, FNI.FISH_NAME, FI.LENGTH from FISH_INFO as FI JOIN FISH_NAME_INFO as FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE (FI.FISH_TYPE, FI.LENGTH) IN (select FISH_TYPE, MAX(LENGTH) FROM FISH_INFO GROUP BY FISH_TYPE)
order by FI.ID asc

-- 물고기 종류별 가장 큰 물고기 출력
-- 물고기 ID 기준 오름차순 