-- 코드를 입력하세요
SELECT II.INGREDIENT_TYPE, SUM(FH.TOTAL_ORDER) as TOTAL_ORDER FROM FIRST_HALF as FH JOIN ICECREAM_INFO as II
ON FH.FLAVOR = II.FLAVOR
GROUP BY II.INGREDIENT_TYPE
order by TOTAL_ORDER asc;


-- 성분 타입 별 총주문량
-- 정렬 기준 총주문량 오름차순